name: Build LaTeX and Release

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write   # allow workflow to create releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex   # replace with your .tex filename
          latexmk_use_lualatex: true  # optional, if you use lualatex

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: document
          path: main.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: document
          path: .

      - name: Get ISO date version
        id: iso_date
        run: echo "version=$(date -u +%Y.%m.%d)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.iso_date.outputs.version }}"
          name: "Arduino book v${{ steps.iso_date.outputs.version }}"
          files: main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
