name: Build LaTeX and Release

on:
  push:
    tags:
      - 'v*'   # trigger only when pushing tags like v1.0.0

permissions:
  contents: write   # allow workflow to create releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex   # replace with your .tex filename
          latexmk_use_lualatex: true  # optional, if you use lualatex

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: document
          path: main.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: document
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Arduino book ${{ github.ref_name }}"
          files: main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
